# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b6da01468aa005ee4e4f39a976ab2eafcc3a00d9f30f2f1e88e67fc33b5bc7989cd6a750db8324d7f76d6346de985e2a430c05137af4f3fb1c5ebb4f308d7e7

test:
  secret_key_base: 7aea43e19910e2838c6e945ac7293307f27ff20df0c7613bafeb48f650f05a16080292ea1053a374ee67f75c0c9de03d823bf8e3666cc99662ec707e0b270faf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
